FROM livemps/mps-min-debian
USER mps
WORKDIR /home/mps
ARG DEBIAN_FRONTEND=noninteractive
RUN cd ~/mps/repo/github.com/mps/mps-installers/installers \
    && git pull \
    && make INST="mpsfolders essentials vim fonts X" install
ENTRYPOINT ["/bin/bash"]
