FROM livemps/mps-min-arch
RUN mkdir -p /mps && cd /mps \
    && git clone https://github.com/livemps/mps-installers \
    && cd mps-installers && git config pull.ff only && git pull \
    && cd installers && make INST=vim install \
    && sudo chmod a+rw -R /mps
USER mps
WORKDIR /home/mps
ENTRYPOINT ["/bin/bash"]
