FROM livemps/mps-min-debian
USER mps
WORKDIR /home/mps
ARG DEBIAN_FRONTEND='noninteractive'
RUN mkdir -p ~/mps/repo/github.com/mps/ && cd ~/mps/repo/github.com/mps/ \
    && git clone https://github.com/livemps/mps-installers \
    && cd mps-installers && git config pull.ff only && git pull 
RUN cd ~/mps/repo/github.com/mps/mps-installers/installers \
    && make INST="mpsfolders vim" install \
    && make INST="mpsfolders essentials vim" status
ENTRYPOINT ["/bin/bash"]
