FROM livemps/mps-min-arch
USER mps
WORKDIR /home/mps
RUN cd ~/mps/repo/github.com/mps/mps-installers/installers \
    && git pull \
    && make INST="mpsfolders essentials" install 
ENTRYPOINT ["/bin/bash"]
