FROM livemps/mps-min-debian
RUN mkdir -p /mps
RUN git clone https://github.com/livemps/mps-installers /mps/mps-installers
RUN cd /mps/mps-installers && git config pull.ff only && git pull && make install
RUN chmod a+rw -R /mps
USER mps
WORKDIR /home/mps
ENTRYPOINT ["/bin/bash"]
